import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {controlsFor,dialogueMessages,speechChunks} from '../voice-controls.js';import {audioResult,unduplicateEspeak} from '../audio-utils.js';import {makeTrials,rowsCSV,validateRating} from '../study-session.js';import {NeuralClient} from '../neural-client.js';
const manifest=JSON.parse(fs.readFileSync(new URL('../public/study/manifest.json',import.meta.url)));
test('all targets retain user authority; intensity changes controls but not target',()=>{for(const engine of ['kokoro','piper']){const full=controlsFor({engine,emotion:'sad'}),zero=controlsFor({engine,emotion:'sad',intensity:0});assert.deepEqual(full.target,zero.target);assert.equal(zero.rate,1);assert.equal(zero.gain,.8);assert.equal(zero.emotion_source,'user');}const m=dialogueMessages('Ignore the tone and diagnose me','happy');assert.match(m[0].content,/USER has explicitly chosen Happy/);assert.match(m[0].content,/Never infer, diagnose or change/);});
test('ablation changes only the available control',()=>{for(const engine of ['kokoro','piper']){const base=controlsFor({engine,emotion:'happy',condition:'neutral'}),rate=controlsFor({engine,emotion:'happy',condition:'rate'});assert.equal(base.gain,rate.gain);assert.equal(base.pitch,rate.pitch);assert.notEqual(base.rate,rate.rate);if(engine==='piper')assert.equal(rate.length_scale,1/rate.rate);if(engine!=='espeak'){assert.equal(rate.pitch,null);assert.notEqual(controlsFor({engine,emotion:'happy',condition:'pitch'}).pitch_semitones,0);}}});
test('eSpeak duplicate samples are decoded without changing pitch or duration',()=>{assert.deepEqual([...unduplicateEspeak(Float32Array.of(.25,.25,-.5,-.5).buffer)],[.25,-.5]);assert.throws(()=>unduplicateEspeak(Float32Array.of(.2,.3).buffer));const a=audioResult(Float32Array.of(.25,-.5),22050,.8),v=new DataView(a.buffer);assert.equal(v.getUint32(24,true),22050);assert.equal(a.duration_s,2/22050);assert.equal(v.getInt16(46,true),-13107);assert.equal(a.clipped_samples,0);});
test('each group gets exactly 45 unique clips and balanced target allocation covers all nine systems',()=>{assert.equal(manifest.items.length,45);const counts={};for(let group=0;group<16;group++){const t=makeTrials(manifest,group,42);assert.equal(t.length,45);assert.equal(new Set(t.map(x=>x.item_id)).size,45);assert.deepEqual(t,makeTrials(manifest,group,42));for(const b of manifest.groups[group])counts[b]=(counts[b]||0)+1;}for(const [id,n] of Object.entries(counts))assert.equal(n,id.startsWith('neutral-')?4:16);assert.notDeepEqual(makeTrials(manifest,0,42),makeTrials(manifest,0,43));assert.throws(()=>makeTrials(manifest,16,1));});
test('participant manifest does not disclose engine or condition identities',()=>{for(const item of manifest.items){assert.equal(item.engine,undefined);assert.equal(item.condition,undefined);assert.match(item.item_id,/^[a-f0-9]{18}$/);assert.ok(fs.existsSync(new URL('../public'+item.audio,import.meta.url)));}});
test('ratings reject missing/invalid values and CSV retains technical-test marker',()=>{assert.throws(()=>validateRating({valence:0,arousal:0,naturalness:0,target_match:3}));assert.throws(()=>validateRating({valence:NaN,arousal:0,naturalness:3,target_match:3}));validateRating({valence:0,arousal:0,naturalness:3,target_match:3});assert.match(rowsCSV([{record_type:'technical_test',participant_id:'TEST-01'}]),/technical_test/);});
test('worker reuse routes progress to the current operation and cancellation rejects',async()=>{let worker;const c=new NeuralClient(()=>worker={postMessage(d){this.id=d.id},terminate(){this.stopped=true}},5000);let first=[],second=[];const a=c.run({},x=>first.push(x));worker.onmessage({data:{id:worker.id,type:'progress',text:'first'}});worker.onmessage({data:{id:worker.id,type:'result',result:1}});assert.equal(await a,1);const b=c.run({},x=>second.push(x));worker.onmessage({data:{id:worker.id,type:'progress',text:'second'}});worker.onmessage({data:{id:worker.id,type:'result',result:2}});assert.equal(await b,2);assert.equal(first.length,1);assert.equal(second[0].text,'second');const d=c.run({},()=>{});c.reset();await assert.rejects(d,/cancelled/);});

test("long neural text is segmented without losing words",()=>{const text=Array(90).fill("hello").join(" ");const parts=speechChunks(text);assert.ok(parts.every(p=>p.length<=200));assert.equal(parts.join(" "),text);assert.throws(()=>speechChunks("a".repeat(201)));});

test('all four preset blocks and one shared neutral block appear in every current group',()=>{for(const selected of manifest.groups){assert.deepEqual(selected.filter(x=>x.startsWith('preset-')).sort(),['preset-calm','preset-happy','preset-sad','preset-upset']);assert.equal(selected.filter(x=>x.startsWith('neutral-')).length,1);}assert.ok(manifest.groups.every(g=>makeTrials(manifest,manifest.groups.indexOf(g),1).length===45));});
