import {DatabaseSync,backup} from 'node:sqlite';import {resolve,join,dirname,basename} from 'node:path';
import {mkdirSync,existsSync,readFileSync,writeFileSync,chmodSync,copyFileSync} from 'node:fs';import {createHash} from 'node:crypto';import {fileURLToPath} from 'node:url';
const root=fileURLToPath(new URL('../',import.meta.url)),data=resolve(process.env.ECHO_DATA_DIR||join(root,'data')),source=join(data,'study.sqlite'),dest=resolve(process.argv[2]||join(root,'backups',`echo-${new Date().toISOString().replaceAll(':','-')}.sqlite`));
try{
 if(!existsSync(source))throw Error('No database yet. Start the server first.');if(existsSync(dest)||existsSync(dest+'.audio'))throw Error('Backup destination already exists; choose a new filename.');mkdirSync(dirname(dest),{recursive:true,mode:0o700});
 const db=new DatabaseSync(source,{readOnly:true});try{await backup(db,dest);}finally{db.close();}chmodSync(dest,0o600);
 const snapshot=new DatabaseSync(dest,{readOnly:true});let rows;try{rows=snapshot.prepare('SELECT object_key,sha256 FROM interactive_audio').all();}finally{snapshot.close();}
 for(const r of rows){if(!/^interactive\/X-[A-F0-9]{32}\/[0-9]+-[a-f0-9]{64}\.wav$/.test(r.object_key))throw Error('Invalid archived audio path');const file=join(data,'audio',r.object_key),target=join(dest+'.audio',r.object_key);if(createHash('sha256').update(readFileSync(file)).digest('hex')!==r.sha256)throw Error('Audio changed or is unavailable. Stop the server and retry to a new destination.');mkdirSync(dirname(target),{recursive:true,mode:0o700});copyFileSync(file,target);chmodSync(target,0o600);}
 writeFileSync(dest+'.manifest.json',JSON.stringify({version:'echo-backup-v2',database:basename(dest),audio_directory:basename(dest)+'.audio',audio_count:rows.length,files:rows,restore:'Stop server; restore database as data/study.sqlite and companion directory contents as data/audio. Do not replace auth files unless intentionally restoring researcher authentication.'},null,2),{mode:0o600});
 console.log(`Consistent SQLite backup and ${rows.length} verified WAVs created: ${dest}\nKeep the .manifest.json and .audio companion with this backup.`);
}catch(error){console.error(error.message);console.error('An incomplete destination may remain. Only a backup with its completed manifest is ready for restoration.');process.exitCode=1;}
